version: "3"
services:
  eflint:
    build: .
    ports:
      - "0.0.0.0:5000:5000"
    tty: true
    volumes:
      - ./data:/data
    command: ["eflint-server", "/data/in-flight.eflint", "5000", "--debug"]
  lab:
    image: jupyter/base-notebook
    ports:
      - "0.0.0.0:9999:9999"
    volumes:
     - ./notebooks/:/home/jovyan/notebooks
     - ./data:/home/jovyan/data
    environment:
      - JUPYTER_ENABLE_LAB=1
    command:
      - jupyter
      - lab
      - --ServerApp.ip='*'
      - --ServerApp.port=9999
      - --no-browser
      - --ServerApp.password=''
      - --ServerApp.token=''
      - --allow-root